[project]
name = "emitoner-dhko25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "openai>=2.3.0",
    "pandas>=2.3.3",
    "streamlit>=1.50.0",
]
